runtime: python
env: flex
entrypoint: gunicorn -b :$PORT InBetween.wsgi

beta_settings:
        cloud_sql_instances: strange-bird-199717:us-west1:strange-test

runtime_config:
        python_version: 3
